### ISSUE TITLE
音楽再生時に再生途中で止まってしまう

### ISSUE THREAD

**Issue by Siwo951** [SehataKuro/Giratina#72]
YouTubeを再生中に発生 niconicoは処理的に起こらなそう
キューがある場合には次の曲が再生される事から最後まで再生した判定になってる可能性
StreamをTrueにする前はこの現象は起きてなかったっぽいからストリーミングの処理で何かつまずいてそうな気が

**Comment by SehataKuro** [comment]
niconicoを再生中にも同じ現象がありました
niconicoもストリーミングに変えてから起きているので原因は同じかもしれない

**Comment by SehataKuro** [comment]
![image](https://user-images.githubusercontent.com/75165625/177056500-823941e2-9108-4e9b-93f3-6f0df7867c6c.png)
曲が止まった時のherokuのエラーログです

**Comment by SehataKuro** [comment]
デバッガーたち曰く、二曲以上を流すとき、つまりキューを使ってる時に飛びやすいらしいです

**Comment by SehataKuro** [comment]
曲が止まった時のログです

**Comment by SehataKuro** [comment]
![image](https://user-images.githubusercontent.com/75165625/180471777-e260c0ff-69a9-4423-b995-48e0a7af9cc3.png)

**Comment by neko252222** [comment]
この事例のエラーと似てると思います
治せますかね
https://stackoverflow.com/questions/58892635/discord-py-and-youtube-dl-read-error-and-the-session-has-been-invalidated-fo

**Comment by neko252222** [comment]
FFMPEG_OPTIONSの中身ですが、"options"ではなく"before_options"での指定が正しいのでは無いでしょうか？
海外スレを参考に修正しました。様子見で宜しくお願いします

before
```json
FFMPEG_OPTIONS = {
    "options": "-vn -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 4962 -timeout 2000000000"
}

```

after
```json
FFMPEG_OPTIONS = {
    "before_options": "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5",
    "options": "-vn"
}
```

**Comment by neko252222** [comment]
問題が再発しています。

**Comment by SehataKuro** [comment]
配信に対応できるようにいじっていたFFMPEG_OPTIONSの変更を戻しました
これで様子見をお願いします

**Comment by SehataKuro** [comment]
最近は見られなくなったので閉じます
